In [1]:
import numpy as np
#A = np.matrix([ [

A=np.matrix([[3.,2.,4.], [1.,1.,2.], [4.,3.,2.]])
print(A)


[[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3.  2.]]


In [17]:
def matrizM():
    if (np.linalg.det(A)!=0):
        M=np.zeros((3,3))
        for j in range (3):
            for m in range (3):
                if (m==j):
                    M[j][m]=1

        for k in range (1):
            for i in range (k+1, 3):
                m=A[i, k]/A[k, k]
                M[i, k]=m*(-1)

    return M


M=matrizM()
print('M\n', M)
A1=(matrizM()*A)

def matrizM1():
    if (np.linalg.det(A)!=0):
        M1=np.zeros((3,3))
        for j in range (3):
            for m in range (3):
                if (m==j):
                    M1[j][m]=1

        for k in range (1, 3):
            for i in range (k+1, 3):
                m=A[i, k]/A[k, k]
                M1[i, k]=m*(-1)

                
    return M1

def bFinal(b):
    return np.dot(M,b)
    
    


M1 = matrizM1()
print('M1\n', M1)
print('A1\n', A1)
matrizFinal = M1*A1
print('Matriz A final\n', matrizFinal)
b=np.array([1,2,3])
b = bFinal(b)
print('b final\n', b)




M
 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]
M1
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -3.  1.]]
A1
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]
Matriz A final
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.         -0.66666667 -5.33333333]]
b final
 [ 1.          1.66666667  1.66666667]
